import { v4 as uuidv4 } from "uuid";
import { QueryInterface } from "sequelize";

const EMPLOYEE_COUNT = 10000;
const BATCH_SIZE = 1000;

const firstNames = [
  "Aarav",
  "Emma",
  "Liam",
  "Olivia",
  "Noah",
  "Sophia",
  "Ethan",
  "Mia",
  "Lucas",
  "Ava",
  "Arjun",
  "Priya",
  "James",
  "Emily",
  "Daniel",
  "Sarah",
  "Ryan",
  "Grace",
  "Aditya",
  "Ananya",
];

const lastNames = [
  "Sharma",
  "Smith",
  "Patel",
  "Johnson",
  "Williams",
  "Brown",
  "Singh",
  "Davis",
  "Wilson",
  "Taylor",
  "Kumar",
  "Anderson",
  "Thomas",
  "Martin",
  "Lee",
  "Clark",
  "Walker",
  "Hall",
  "Young",
  "King",
];

const departments = [
  {
    name: "Engineering",
    jobs: [
      "Software Engineer",
      "Senior Software Engineer",
      "Staff Engineer",
      "Engineering Manager",
      "DevOps Engineer",
    ],
  },
  {
    name: "Product",
    jobs: [
      "Product Manager",
      "Senior Product Manager",
      "Product Designer",
      "Product Analyst",
    ],
  },
  {
    name: "HR",
    jobs: [
      "HR Executive",
      "HR Business Partner",
      "HR Manager",
      "Talent Acquisition Specialist",
    ],
  },
  {
    name: "Finance",
    jobs: [
      "Financial Analyst",
      "Accountant",
      "Senior Accountant",
      "Finance Manager",
    ],
  },
  {
    name: "Sales",
    jobs: [
      "Sales Executive",
      "Account Executive",
      "Sales Manager",
      "Business Development Manager",
    ],
  },
  {
    name: "Marketing",
    jobs: [
      "Marketing Specialist",
      "Content Strategist",
      "Growth Manager",
      "Marketing Manager",
    ],
  },
  {
    name: "Operations",
    jobs: [
      "Operations Analyst",
      "Operations Executive",
      "Operations Manager",
    ],
  },
  {
    name: "Customer Success",
    jobs: [
      "Customer Success Executive",
      "Customer Success Manager",
      "Support Specialist",
    ],
  },
];

const countries = [
  {
    name: "India",
    currency: "INR",
    minSalary: 400_000,
    maxSalary: 5_000_000,
  },
  {
    name: "United States",
    currency: "USD",
    minSalary: 45_000,
    maxSalary: 250_000,
  },
  {
    name: "United Kingdom",
    currency: "GBP",
    minSalary: 30_000,
    maxSalary: 180_000,
  },
  {
    name: "Germany",
    currency: "EUR",
    minSalary: 35_000,
    maxSalary: 190_000,
  },
  {
    name: "Canada",
    currency: "CAD",
    minSalary: 45_000,
    maxSalary: 220_000,
  },
  {
    name: "Australia",
    currency: "AUD",
    minSalary: 50_000,
    maxSalary: 240_000,
  },
  {
    name: "Singapore",
    currency: "SGD",
    minSalary: 45_000,
    maxSalary: 220_000,
  },
  {
    name: "Japan",
    currency: "JPY",
    minSalary: 4_000_000,
    maxSalary: 20_000_000,
  },
];

function getSalary(
  min: number,
  max: number,
  index: number
): number {
  /**
   * Deterministic salary generation.
   *
   * Gives variation without Math.random().
   */
  const percentage = ((index * 37) % 100) / 100;

  return Math.round(
    min + (max - min) * percentage
  );
}

function getHireDate(index: number): Date {
  const year = 2015 + (index % 11);

  const month = index % 12;

  const day = (index % 28) + 1;

  return new Date(
    Date.UTC(year, month, day)
  );
}

export async function up(
  queryInterface: QueryInterface
): Promise<void> {
  const employees = [];
  const salaries = [];

  const now = new Date();

  for (
    let index = 0;
    index < EMPLOYEE_COUNT;
    index++
  ) {
    const employeeId = uuidv4();

    const firstName =
      firstNames[index % firstNames.length];

    const lastName =
      lastNames[
        Math.floor(index / firstNames.length) %
          lastNames.length
      ];

    const department =
      departments[index % departments.length];

    const jobTitle =
      department.jobs[
        index % department.jobs.length
      ];

    const country =
      countries[index % countries.length];

    const hireDate = getHireDate(index);

    employees.push({
      id: employeeId,

      // employeeCode is generated by PostgreSQL.

      first_name: firstName,

      last_name:lastName,

      email:
        `${firstName}.${lastName}.${index + 1}@acme.com`
          .toLowerCase(),

      department: department.name,

      job_title: jobTitle,

      country: country.name,

      hire_date: hireDate,

      // Around 95% ACTIVE.
      status:
        index % 20 === 0
          ? "INACTIVE"
          : "ACTIVE",

      created_at: now,

      updated_at: now,
    });

    salaries.push({
      id: uuidv4(),

      employee_id: employeeId,

      base_salary: getSalary(
        country.minSalary,
        country.maxSalary,
        index
      ),

      currency: country.currency,

      effective_from: hireDate,

      reason: "Initial salary",

      created_at: now,
    });
  }

  for (
    let start = 0;
    start < EMPLOYEE_COUNT;
    start += BATCH_SIZE
  ) {
    await queryInterface.bulkInsert(
      "employees",
      employees.slice(
        start,
        start + BATCH_SIZE
      )
    );
  }

  for (
    let start = 0;
    start < EMPLOYEE_COUNT;
    start += BATCH_SIZE
  ) {
    await queryInterface.bulkInsert(
      "employee_salaries",
      salaries.slice(
        start,
        start + BATCH_SIZE
      )
    );
  }

  console.log(
    `Seeded ${EMPLOYEE_COUNT} employees`
  );
}

export async function down(
  queryInterface: QueryInterface
): Promise<void> {
  await queryInterface.bulkDelete(
    "employee_salaries",
    {}
  );

  await queryInterface.bulkDelete(
    "employees",
    {}
  );

  await queryInterface.sequelize.query(`
    ALTER SEQUENCE employee_code_seq
    RESTART WITH 1
  `);
}